name: Push Tags

on:
  push:
    tags:
      - '*'

jobs:
  save-container:
    strategy:
      matrix:
        py_version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    name: create and save container
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker pull ghcr.io/micro-fan/python:latest || true
    - run: >
        PY_VERSION=python${{ matrix.py_version }}
        TAG_NAME=${{ env.RELEASE_VERSION }}-py${{ matrix.py_version }}
        make push_ghcr_image
