name: Push Latest

on:
  push:
    branches:
      - 'master'

jobs:

  save-container:
    name: create and save container
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: docker pull ghcr.io/micro-fan/python:latest; true
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - run: TAG_NAME=latest make push_ghcr_image
