name: Push Latest

on:
  push:
    branches:
      - 'master'

jobs:
  save-container:
    strategy:
      matrix:
        py_version:
          - '3.9'
          - '3.10'
          - '3.11'
    name: create and save container
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - run: docker pull ghcr.io/micro-fan/python:latest || true
    - run: >
        PY_VERSION=${{ matrix.py_version }}
        TAG_NAME=latest-py${{ matrix.py_version }}
        make push_ghcr_image
    - run: >
        BUILD_HELM=1
        PY_VERSION=${{ matrix.py_version }}
        TAG_NAME=latest-py${{ matrix.py_version }}-helm
        make push_ghcr_image
